<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="US9XPMBN2Q" failures="0" tests="1" name="sew.ai.tests.csp.AdminNotificationTests" time="27.035" errors="1" timestamp="2023-04-05T15:13:28 IST" skipped="0">
  <testcase classname="sew.ai.tests.csp.AdminNotificationTests" name="verifyProblemsSigningInCSPNotificationRequest" time="27.035">
    <error message="Cannot invoke &quot;sew.ai.models.User.getEmailId()&quot; because &quot;user&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "sew.ai.models.User.getEmailId()" because "user" is null
at sew.ai.api.pojos.loginHelp.ProblemSignInPayload.<init>(ProblemSignInPayload.java:35)
at sew.ai.api.endpoints.auth.LoginSupportEndpoint.buildRequestSpecToCreateProblemSignInReq(LoginSupportEndpoint.java:40)
at sew.ai.api.endpoints.auth.LoginSupportEndpoint.generateProblemsSigningInSCPRequest(LoginSupportEndpoint.java:33)
at sew.ai.steps.csp.AdminNotificationSteps.generateProblemSigningInAPIRequest(AdminNotificationSteps.java:1609)
at sew.ai.tests.csp.AdminNotificationTests.verifyProblemsSigningInCSPNotificationRequest(AdminNotificationTests.java:889)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyProblemsSigningInCSPNotificationRequest -->
  <system-out/>
</testsuite> <!-- sew.ai.tests.csp.AdminNotificationTests -->
